# Generated by Django 5.2.8 on 2025-11-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(help_text='Enter order is:')),
                ('order_name', models.CharField(help_text='Enter order name:', max_length=100)),
                ('order_description', models.CharField(help_text='Enter order description:', max_length=100)),
                ('quantity', models.IntegerField(help_text='Enter quantity:')),
                ('order_date', models.DateField(help_text='Enter order date:')),
            ],
        ),
    ]
